export const serviceMessageStream = Symbol('serviceMessageStream')
export const webrtcService = Symbol('webrtcServiceStream')
export const pendingRequests = Symbol('pedingRequest')
export const setPendingRequest = Symbol('pedingRequest')
export const getPendingRequest = Symbol('pedingRequest')
